name: secret practice

on:
  workflow_dispatch:

jobs:
  job1: # Doit être aligné sous 'jobs:'
    runs-on: ubuntu-latest # Doit être aligné sous 'job1:'

    steps:
      - name: afficher le secret
        # Utiliser la clé 'run:' pour la commande
        # Utiliser 'env:' pour passer le secret comme variable d'environnement (méthode la plus sûre)
      - run: echo "Le secret est : $MON_SECRET"
        env:
          MON_SECRET: ${{ secrets.BRYAM }}
