name: secrets

on:

   workflow_dispatch:
  
   


jobs:
  job_ex_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Tester l'exercice secret
        run: echo "Workflow déclenché {{ secrets.MONSECRET }}"
        
